name: Build and Deploy
on:
  push:
    branches:
      - main
  
permissions:
  contents: read
  pages: write
  id-token: write

 
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn install
      - run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: true
          repository: sindhura-kaparthi/speech-assistant-frontend-test
          ref: main
          path: speech-assistant-frontend-test
      - name: push artifact
        working-directory: speech-assistant-frontend-test/
        run: |
          git config user.name sindhura-kaparthi
          git config user.email sindhura.kaparthi@thoughtworks.com
          git remote set-url origin https://sindhura-kaparthi:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git subtree push --prefix dist origin gh-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
