name: Build and Deploy
on:
  push:
    branches: 
      - main
jobs:
  build-deploy:
    name: Build , Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn install
      - run: yarn lint
      - run: yarn typescript
      - run: yarn test
      - run: yarn build
      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist/bundle

